### ISSUE TITLE
Create folder structure

### ISSUE THREAD

**Issue by br0wn** [taqat/components#1]
Create folders based on specified folder structure from the README.

**Comment by rajukumartg** [comment]
Hi,

Where we have to put the components folders. There will be another folder for the components.

![image.png](https://zube.io/files/taqat/4a318cbff552bf5d0b90102749574703-image.png)

**Comment by br0wn** [comment]
It would be like this 
```
- tazman-backend/
    - core/
    - symfony/
- components/
```
